name: Mplas
version: '${project.version}'
main: org.mplas.mplas.Mplas
api-version: '1.20'
commands:
  Mplas:
    description: вывести информацию о плагине
    usage: /<command>
    aliases:
      - plas